name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Update pip
      run: pip install --upgrade pip

    - name: Install system dependencies for PyArrow
      run: sudo apt-get install -y libarrow-dev libparquet-dev

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python test.py
